// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'payeewise';

  static const String assets_images_logo_main_png = 'assets/images/logo_main.png';
  static const String payeewise$assets_images_logo_main_png = 'packages/payeewise/assets/images/logo_main.png';
}
